pipeline {
    agent any 
      stages {
          stage('Test') {
              agent {
	              dockerfile {
                           filename 'Dockerfile.build'
                  	       dir "web"
                  }
	          } 
              steps {
                  script{
                       try {
                         sh "pytest -v tests/"
                       }
                       catch(Exception e) {
                           echo "test failed"
			               currentBuild.result = 'Failed' 
                       }
                  }
              }
          }
          stage('Build') { 
		      environment {
                        GC_KEY = 'shaked'
                        google_project_id = 'shaked-311109'
                        image_name = 'web'
		      }
              steps {
                  dir("web") {
		            sh "docker build -t eu.gcr.io/${google_project_id}/${image_name}:${BUILD_NUMBER} ."
                    sh "docker push eu.gcr.io/${google_project_id}/${image_name}:${BUILD_NUMBER}"
                  }
              }
           }
      }
}
